jrief/django-websocket-redis

ws4redis/settings.py
ws4redis/wsgi_server.py

see issue #67 for detailed user case

Add flexibility to handle customized authentication

---

ws4redis/models.py

User model can't contain such attribute, for example in custom User model.

Check for groups attribute

---

TODO.txt

Hi, jrief, I noticed there are some typos in TODO.txt, may this PR do some help, and thanks again for your project, it helped me a lot.

Fix typos in TODO.txt

---

ws4redis/subscriber.py
ws4redis/websocket.py
ws4redis/wsgi_server.py

This is kind of three pull requests in one, but I had to make these changes to get everything ready for production.
1. redis_cleanup - close redis socket connections better upon websocket disconnect
2. nginx_safe_response - when there was an exception before the websocket handshake, and we were using uwsgi, the http headers were not written.  This caused trouble when proxying behing nginx
3. Various error message improvements - added a little more info to the logger to help debugging
If you accept this, please ignore my other pull requests.
If this is too much, you can take one or two of the other pull requests without problem

Various cleanup

---

setup.py
ws4redis/__init__.py

Hi,
since you said you didn't have much time for ws4redis, I prepared the files for a version bump if you feel it's appropriate.
Cheers!

version bump

---

examples/chatserver/tests/test_chatclient.py
ws4redis/django_runserver.py

This is a fixup for and incorporates PR #151 and fixes issue #152

Support sec websocket protocol

---

docs/changelog.rst

As the title says, I fixed a typo in my name in the changelog :)

Fix typo in name in changelog

---

docs/usage.rst
ws4redis/static/js/ws4redis.js

This Pull Request adds a connection callback to the websocket javascript.

Connect callback

---

docs/installation.rst

update doc now django use migrate instead of syncdb

update doc now django use migrate instead of syncdb

---

ws4redis/redis_store.py

Deal with a not-set WS4REDIS_HEARTBEAT

---

examples/chatserver/templates/chat_base.html

See:
- http://staticfiles.productiondjango.com/blog/stop-using-static-url-in-templates/
- https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#std:templatetag-static
Thanks for this awesome library!

Use staticfiles, not STATIC_URL

---

ws4redis/wsgi_server.py

My first attempt in regards to Issue 191.

Added the _websockets attribute to store active connections

---

ws4redis/publisher.py

This will support unix domain sockets (closes #212) but won't drop connectionpool support (compare PR #213).

Support ConnectionPool and Unix Domain Sockets

---

ws4redis/django_runserver.py
ws4redis/websocket.py
ws4redis/wsgi_server.py

Hey there, I had to make this changes so my django 1.11 project would work... Let me know if you'd like me  to fix or do something differently so they can be merged

Make it work on django 1.11

---

ws4redis/publisher.py

fix support for Unix Domain Sockets

---

ws4redis/wsgi_server.py

Fix websocket closed status code compatibility with Django v1.11

---

examples/chatserver/tests/test_chatclient.py
ws4redis/redis_store.py
ws4redis/websocket.py

Closes #236.
~~Also adds Python 3.5 and 3.6 to Travis-CI.~~

Handle binary messages in Python 3

---

ws4redis/django_runserver.py

Following https://github.com/django/django/pull/8043, handlers have been overridden to use HTTP/1.1
refs #206

Issue #206 Fix Safari websocket problem on runserver

---

docs/installation.rst

Clarify WS4REDIS_EXPIRE to include instructions on how to turn if off.

Fixes #250

---

README.md

Avoids duplicating information in 2 pages and reduces maintainence.

Remove What's New and link to changelog.rst

---

.travis.yml
ws4redis/django_runserver.py

Add Django 2.1.5 and latest support.
