jrief/django-websocket-redis

- ws4redis/subscriber.py
- ws4redis/wsgi_server.py
Previously the redis subscriber wouldn't be closed or return to the
connection pool on websocket disconnect.  When running a few load tests
(each eg. 1000 connections) after another, we noticed that the later
load tests had more failures due to too many file handles.
The StrictRedis would release the connection on __del__ which is
fine with low churn, as the garbage collector would eventually close
the socket.  But to pro-actively close unneeded sockets, we must
explicitly release them ourselves.
This code is my own, but I was inspired by the pull request from
https://github.com/kaipeng/django-websocket-redis
> Cleanup redis connections when websockets disconnect.

- .gitignore
- CHANGELOG.rst
- TODO.txt
- docs/testing.rst
- examples/chatserver/settings.py
- examples/chatserver/tests/__init__.py
- examples/chatserver/tests/requirements.txt
- examples/chatserver/tests/settings.py
- examples/chatserver/tests/test_chatclient.py
- examples/requirements.txt
@jrief,
I updated the example project and the docs at *docs/testing.rst* to use Django 1.7, and updated the pip requirements.txt to be the same file between *test* and *chatserver*.  I noted the changes in a CHANGELOG.rst file.
I am still working on getting all tests to pass.  I was getting an error with Django *LiveServerTestCase* no recognizing *self.client.session*. I will work on those more. Overall 7 of 12 tests passed.  When I manually tested it though, everything looked fine...
If I changed the example project too much, please let me know.
I am planning to try and you *ws4redis* with a simple app with Django 1.7, so I wanted to contribute this if possible.
Thanks
> update example project

- ws4redis/wsgi_server.py
in django 1.8.2
manage.py runserver
causes
django-websocket-redis/ws4redis/wsgi_server.py:12: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
from django.utils.importlib import import_module
the deprecation warning is documented here:
https://docs.djangoproject.com/en/1.8/releases/1.7/#django-utils-dictconfig-django-utils-importlib
see also here
http://stackoverflow.com/questions/29931979/recommended-practice-for-using-import-module-in-django-1-8?answertab=active#tab-top
> fix deprecation warning for django 1.9 [fix #98]

- ws4redis/wsgi_server.py
This commit removes the check for middleware by name, always initializing the session if the session cookie is present, and always setting the user.  This has side effect that `request.user` may be set to AnonymousUser even if contrib.auth is not active.
> Support custom session and auth middleware

- ws4redis/wsgi_server.py
Django removed some deprecated code, which ws4redis still used.
Quote from the Django 1.9 release notes:
> django.http.responses.REASON_PHRASES and
> django.core.handlers.wsgi.STATUS_CODE_TEXT have been removed. Use
> Python’s stdlib instead: http.client.responses for Python 3 and
> httplib.responses for Python 2.
This commit makes ws4redis use `http.client.responses` instead of
`django.core.handlers.wsgi.STATUS_CODE_TEXT`.
This fixes issue:
https://github.com/jrief/django-websocket-redis/issues/125
> Update deprecated usage of code from Django

- ws4redis/redis_store.py
The `RedisMessage` wrapper only handles `str` or `list` types, but the websocket object's `receive` function returns bytestrings when running uwsgi as a standalone server with Python 3. All websocket messages sent are discarded. This pull request addresses that issue.
> Added RedisMessage support for bytestrings

- ws4redis/redis_store.py
Mutable default args are generally a bad practice, although in this method they do not appear to be altered. I see no downside to using a tuple here instead of a list.
> Change mutable default args in RedisStore._get_message_channels

- docs/usage.rst
The _wrap_user code that converts SELF to the active user needs the request instance. This can be passed through the RedisPublisher constructor.
```
def _wrap_users(users, request):
...
for u in users:
if u is SELF and request and request.user and request.user.is_authenticated():
result.add(request.user.get_username())
....
```
> Add request to RedisPublisher to use SELF

- ws4redis/wsgi_server.py
This commit adds an extra check before sending a heartbeat to ensure
that the websocket has not been closed in the loop.
> Prevent race condition with heartbeat and closed websocket

- ws4redis/websocket.py
Given that the previous code was returning a tuple while `close` expects a an int, I believe @roidelapluie 's fix should also be applied to python 2.
I guess it's just a part of the code we never hit before.
@jrief are you ok with this ?
> fix #135 for python2

- .travis.yml
- examples/chatserver/tests/__init__.py
- examples/chatserver/tests/test_chatclient.py
- examples/requirements.txt
Prior to this commit, the tests were running with Django 1.8 because it
is in requirements.txt, which was installed after the specific version
of Django.
This commit inverts that order, allowing the defined version of Django
to be used for testing.
> Test with the right Django version ; Add and fix 1.9 tests

- docs/testing.rst
This user is created in the loaddata step but the password wasn't previously given.
> Add missing default admin user details

- examples/chatserver/tests/test_chatclient.py
- examples/requirements.txt
- ws4redis/django_runserver.py
This branch adds support for the Sec-WebSocket-Protocol header. Without this change, the websocket will fail to connect if the Sec-WebSocket-Protocol header is uses by the client.
> Add support for Sec-WebSocket-Protocol header

- docs/installation.rst
- docs/usage.rst
- examples/chatserver/tests/test_chatclient.py
- ws4redis/wsgi_server.py
Small patch for `wsgi_server.py` to ensure that users can set `WS4REDIS_ALLOWED_CHANNELS` to a module string as common in most django applications.
Modified UnitTests accordingly and added the setting into configuration docs.
> Making WS4REDIS_ALLOWED_CHANNELS accept strings

- docs/running.rst
The internal routing capabilities of uWSGI is dependent on the PCRE library. My test machine running Ubuntu 14.04 LTS did not include said library out of the box. uWSGI in emperor mode with routing will only server 500 errors for any HTTP request if it was not built with PCRE support. This PR adds a note and troubleshooting info to the docs regarding the matter.
> Added troubleshooting info for running in uWSGI emperor mode

- ws4redis/static/js/ws4redis.js
To be able to act on socket state this adds a method that returns readyState of the internally used WebSocket.
> Exposes WebSocket readyState in WS4Redis

- docs/changelog.rst
- docs/usage.rst
- ws4redis/static/js/ws4redis.js
Some improvements to the javascript API:
- Trying to reconnect when the first attempt (on instantiation) fails.
- Adding 'connecting' and 'disconnected' callback options.
- Adding the 'close' method to the API. When the websocket is closed through this method, there will be no reconnection attempts.
- Adding the following methods to the API to check websocket status: is_connecting, is_connected, is_closing, is_closed.
The documentation was also updated to reflect the changes.
> Improvements in javascript API.

- ws4redis/_compat.py
- ws4redis/publisher.py
- ws4redis/redis_store.py
Django 1.10 deprecates callable `is_authenticated` (among other methods) in favor of using properties. This change introduces a function to check whether a request is authenticated and also make it forward-compatible with Django 1.10 and later.
> make is_authenticated compatible with Django 1.10

- ws4redis/publisher.py
Switched StrictRedis instantiation to settings parameters. Unix sockets can be enabled by providing following WS4REDIS_CONNECTION configuration:
``
WS4REDIS_CONNECTION = {
'unix_socket_path': '/path/to/redis.sock'
}
``
> Enabled use of unix sockets for Redis connection

- ws4redis/wsgi_server.py
refs #232
If WS4REDIS_PROCESS_REQUEST, the string is considered as a path and `django.utils.module_loading.import_string` (or `import_by_path` for older version) is used to do so.
> Allow WS4REDIS_PROCESS_REQUEST to be a string

- docs/installation.rst
See: https://docs.djangoproject.com/en/1.8/releases/1.8/#django-core-context-processors
> Clarify django.core.context_processors has been deprecated after django 1.8

- docs/installation.rst
`ws4redis.store.RedisStore` doesn't exist in 0.5.1 as the module has been moved to `redis_store.py`.
Took the chance to rewrite the settings document to clarify the default behavior and how to extend the base class.
> Clarify WS4REDIS_SUBSCRIBER

- docs/running.rst
There is a small typo in docs/running.rst.
Should read `paths` rather than `pathes`.
> docs: Fix simple typo, pathes -> paths

- docs/running.rst
- ws4redis/static/js/ws4redis.js
There are small typos in:
- docs/running.rst
- ws4redis/static/js/ws4redis.js
Fixes:
- Should read `completely` rather than `completly`.
- Should read `attempts` rather than `attmpts`.
- Should read `attempts` rather than `attemps`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- docs/installation.rst
- ws4redis/publisher.py
* `RedisPublisher` handles `ssl` flag
* Update docs
Btw, i've used [black](https://github.com/ambv/black) for the small parts i've changed. Have you considered using this tool. It really reduces time spent on code formatting and let developers focus on what matters.
In terms of testing, afaik [travis](https://docs.travis-ci.com/user/database-setup/#redis) does not support natively ssl redis-servers. Since modifications relies on well-tested code (`redis.SSLConnection`), i guess it's ok not to test it thoroughly.
> Issue #284 Handle ssl connections
